//botões
let btnDogs = document.querySelector('#btnDogs');
let btnCats = document.querySelector('#btnCats');
let btnBirds = document.querySelector('#btnBirds');
let btnReps = document.querySelector('#btnReps');
//conteúdo de texto
let content = document.querySelector('#content');

//ação onclick
btnDogs.addEventListener('click', () => {
    content.innerHTML = '<h1>Cachorros</h1><p>&nbsp&nbsp&nbsp&nbspLorem ipsum dolor sit amet consectetur adipisicing elit. Beatae maiores quibusdam nisi, atque recusandae quaerat voluptatibus vel nesciunt dignissimos. Voluptas nostrum quaerat cum et beatae molestiae, accusamus laudantium porro eos assumenda harum dolore? Modi, mollitia? Aperiam autem ut voluptatibus? Laborum, ipsam? Fugit, eaque maxime aliquid voluptatum culpa vel atque nemo blanditiis, eos sed necessitatibus deleniti amet sapiente quidem ad soluta! Laboriosam vero nemo voluptatem, amet nesciunt quia. Placeat culpa nulla ex voluptates, atque sed ad odio doloremque? Totam recusandae ipsum dignissimos. Laudantium magni tempore soluta. Enim corrupti, ab, minus qui recusandae excepturi consectetur asperiores aspernatur sint totam voluptatem iste, rem consequatur! Error rem nobis eligendi quam voluptas nisi, commodi ut, voluptatum in minus, incidunt magnam odio tempora vitae. Aperiam iure porro hic itaque facere deleniti voluptatibus perferendis animi minima qui officiis, error cum. Quo, possimus voluptatem odio corporis aliquid exercitationem facere sit neque distinctio, dolore maiores commodi illum ab nihil?</p>';
});
btnCats.addEventListener('click', () => {
    content.innerHTML = '<h1>Gatos</h1><p>&nbsp&nbsp&nbsp&nbspLorem ipsum dolor sit amet consectetur adipisicing elit. At ratione dignissimos exercitationem, veritatis vel ex aspernatur commodi laboriosam iure consectetur nobis quibusdam sed! Ad consequuntur iste laborum maiores reprehenderit ab quo, vitae tempora magni facilis numquam magnam consequatur esse! Ullam laboriosam sed molestiae sit, eveniet illum odit quasi repellat dolore alias quos hic quaerat id et corrupti ex! Delectus quo nostrum cupiditate temporibus molestiae quisquam quae modi! Illum temporibus id corporis quos quam eum, voluptate libero molestiae minus velit corrupti cupiditate hic inventore placeat optio doloremque iste odio fugit aliquam. Sint repellat suscipit iusto nemo. Vero ea voluptatem dignissimos maxime nobis dicta laborum tempora. Nostrum distinctio asperiores suscipit vero a? Excepturi quis nam sed accusantium commodi enim sint, eaque cumque, dolore magni tenetur esse deserunt voluptatibus. Esse enim deserunt fugiat in cumque quisquam hic exercitationem aut ipsum, accusantium, distinctio doloribus quas id officia, repellat illum. Deserunt, quisquam, ipsa qui eaque dolorum neque ea, maxime non quae tempore tenetur doloribus praesentium est assumenda? Quas non quasi cum eaque hic, animi asperiores voluptates dolores omnis aliquid, voluptatem cumque nobis rem dolorem dolore molestias? Incidunt ullam voluptatibus ipsam nesciunt et. Ab, aliquid itaque animi voluptatibus laudantium, error iusto dolorum facilis tempore sequi vitae.</p>';;
});
btnBirds.addEventListener('click', () => {
    content.innerHTML = '<h1>Aves</h1><p>&nbsp&nbsp&nbsp&nbspLorem ipsum dolor sit amet, consectetur adipisicing elit. Officia veniam delectus earum commodi rerum enim sequi dolor inventore? Odio ut velit obcaecati ad reiciendis ipsum vitae, ipsam autem perferendis porro magnam delectus nulla excepturi placeat saepe praesentium sequi quod officia enim, numquam expedita voluptatum, dolores necessitatibus. Pariatur perferendis, ullam hic officiis possimus totam nesciunt tempora veritatis laudantium est fugiat officia odit veniam alias illum dolorem dolor minima aspernatur nemo id beatae doloremque. Magnam odit, incidunt repellendus nihil corporis nisi, temporibus blanditiis magni, nemo ipsam necessitatibus quas eligendi repellat aliquid dolorem voluptatum esse! Quia deserunt voluptas vel laudantium praesentium nihil alias numquam, modi explicabo officiis ratione aperiam sunt rerum architecto amet ab itaque atque aliquam quisquam. Dolores, esse. Fugiat quam error nesciunt voluptatibus nam, recusandae beatae magnam fuga officiis soluta vitae! Nesciunt quaerat dolore voluptas rerum soluta labore, quis alias asperiores sapiente deleniti enim odio nulla minima provident qui. Quibusdam exercitationem recusandae quaerat rerum quia est earum, eligendi laudantium, excepturi, tempora laboriosam pariatur officia enim beatae? Voluptates expedita asperiores libero eos?</p>';;
});
btnReps.addEventListener('click', () => {
    content.innerHTML = '<h1>Répteis</h1><p>&nbsp&nbsp&nbsp&nbspLorem ipsum, dolor sit amet consectetur adipisicing elit. Neque reiciendis placeat beatae commodi. Ducimus, recusandae officiis! Eligendi aliquam optio quisquam enim laboriosam pariatur consequuntur deserunt repellat. Excepturi omnis odit doloremque cumque iste enim amet a nisi, ducimus obcaecati consequuntur, quis dolorem. Minus voluptatem unde, ex eius, facilis mollitia dolores maiores exercitationem omnis iusto, repellat perferendis neque illum ipsum nulla aliquid. Soluta nam illum optio quia nihil consectetur similique deserunt. Veritatis, necessitatibus! Esse vel deleniti exercitationem amet? Explicabo delectus ab harum deserunt repudiandae, quam nisi vel totam praesentium in, eos necessitatibus accusantium eveniet accusamus maxime! Suscipit sapiente optio fuga dicta debitis sed accusamus illo rem cum maiores enim, deleniti modi commodi quaerat quasi esse hic dignissimos error non ducimus quia quis. Enim dolores dolore minima dolorum adipisci deleniti illum culpa, necessitatibus quasi pariatur hic ipsum numquam nesciunt odio saepe ea corrupti. Dignissimos tempore asperiores exercitationem consequatur minima beatae, minus, reiciendis tempora possimus corporis, molestias libero. Quidem earum deleniti voluptatum, odit itaque repellendus, vitae doloribus numquam tempora nostrum architecto assumenda dolorem quis. Dolore, beatae delectus inventore modi consectetur distinctio aperiam illum error in eius aspernatur eveniet fuga!</p>';;
});